spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_redlock
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
